"""SDK runtime server — turns @workflow-decorated functions into HTTP services.

Imported and run inside per-workflow containers (CMD line of the Dockerfile
generated by `genai-platform deploy`). One container = one workflow function
= one FastAPI app, picked by response_mode (sync / stream / async).

Book: "Designing AI Systems" — Listings 8.3-8.12.
"""

from .server import build_app, find_workflow

__all__ = ["build_app", "find_workflow"]
