# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import data_pb2 as data__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataServiceStub(object):
    """Listing 5.24
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateIndex = channel.unary_unary(
                '/data.DataService/CreateIndex',
                request_serializer=data__pb2.CreateIndexRequest.SerializeToString,
                response_deserializer=data__pb2.IndexResponse.FromString,
                _registered_method=True)
        self.GetIndex = channel.unary_unary(
                '/data.DataService/GetIndex',
                request_serializer=data__pb2.GetIndexRequest.SerializeToString,
                response_deserializer=data__pb2.IndexResponse.FromString,
                _registered_method=True)
        self.ListIndexes = channel.unary_unary(
                '/data.DataService/ListIndexes',
                request_serializer=data__pb2.ListIndexesRequest.SerializeToString,
                response_deserializer=data__pb2.ListIndexesResponse.FromString,
                _registered_method=True)
        self.DeleteIndex = channel.unary_unary(
                '/data.DataService/DeleteIndex',
                request_serializer=data__pb2.DeleteIndexRequest.SerializeToString,
                response_deserializer=data__pb2.DeleteIndexResponse.FromString,
                _registered_method=True)
        self.IngestDocument = channel.unary_unary(
                '/data.DataService/IngestDocument',
                request_serializer=data__pb2.IngestDocumentRequest.SerializeToString,
                response_deserializer=data__pb2.IngestJobResponse.FromString,
                _registered_method=True)
        self.GetIngestJob = channel.unary_unary(
                '/data.DataService/GetIngestJob',
                request_serializer=data__pb2.GetIngestJobRequest.SerializeToString,
                response_deserializer=data__pb2.IngestJobResponse.FromString,
                _registered_method=True)
        self.ListDocuments = channel.unary_unary(
                '/data.DataService/ListDocuments',
                request_serializer=data__pb2.ListDocumentsRequest.SerializeToString,
                response_deserializer=data__pb2.ListDocumentsResponse.FromString,
                _registered_method=True)
        self.GetDocument = channel.unary_unary(
                '/data.DataService/GetDocument',
                request_serializer=data__pb2.GetDocumentRequest.SerializeToString,
                response_deserializer=data__pb2.DocumentMetadataResponse.FromString,
                _registered_method=True)
        self.DeleteDocument = channel.unary_unary(
                '/data.DataService/DeleteDocument',
                request_serializer=data__pb2.DeleteDocumentRequest.SerializeToString,
                response_deserializer=data__pb2.DeleteDocumentResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/data.DataService/Search',
                request_serializer=data__pb2.SearchRequest.SerializeToString,
                response_deserializer=data__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.HybridSearch = channel.unary_unary(
                '/data.DataService/HybridSearch',
                request_serializer=data__pb2.HybridSearchRequest.SerializeToString,
                response_deserializer=data__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.RegisterParser = channel.unary_unary(
                '/data.DataService/RegisterParser',
                request_serializer=data__pb2.RegisterParserRequest.SerializeToString,
                response_deserializer=data__pb2.RegisterParserResponse.FromString,
                _registered_method=True)
        self.RegisterChunkingStrategy = channel.unary_unary(
                '/data.DataService/RegisterChunkingStrategy',
                request_serializer=data__pb2.RegisterChunkingStrategyRequest.SerializeToString,
                response_deserializer=data__pb2.RegisterChunkingStrategyResponse.FromString,
                _registered_method=True)


class DataServiceServicer(object):
    """Listing 5.24
    """

    def CreateIndex(self, request, context):
        """Index management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListIndexes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestDocument(self, request, context):
        """Document ingestion
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIngestJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDocuments(self, request, context):
        """Document management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Search
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HybridSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterParser(self, request, context):
        """Dynamic code loading for custom parsers and chunking strategies
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterChunkingStrategy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateIndex,
                    request_deserializer=data__pb2.CreateIndexRequest.FromString,
                    response_serializer=data__pb2.IndexResponse.SerializeToString,
            ),
            'GetIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIndex,
                    request_deserializer=data__pb2.GetIndexRequest.FromString,
                    response_serializer=data__pb2.IndexResponse.SerializeToString,
            ),
            'ListIndexes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListIndexes,
                    request_deserializer=data__pb2.ListIndexesRequest.FromString,
                    response_serializer=data__pb2.ListIndexesResponse.SerializeToString,
            ),
            'DeleteIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteIndex,
                    request_deserializer=data__pb2.DeleteIndexRequest.FromString,
                    response_serializer=data__pb2.DeleteIndexResponse.SerializeToString,
            ),
            'IngestDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestDocument,
                    request_deserializer=data__pb2.IngestDocumentRequest.FromString,
                    response_serializer=data__pb2.IngestJobResponse.SerializeToString,
            ),
            'GetIngestJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIngestJob,
                    request_deserializer=data__pb2.GetIngestJobRequest.FromString,
                    response_serializer=data__pb2.IngestJobResponse.SerializeToString,
            ),
            'ListDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDocuments,
                    request_deserializer=data__pb2.ListDocumentsRequest.FromString,
                    response_serializer=data__pb2.ListDocumentsResponse.SerializeToString,
            ),
            'GetDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDocument,
                    request_deserializer=data__pb2.GetDocumentRequest.FromString,
                    response_serializer=data__pb2.DocumentMetadataResponse.SerializeToString,
            ),
            'DeleteDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDocument,
                    request_deserializer=data__pb2.DeleteDocumentRequest.FromString,
                    response_serializer=data__pb2.DeleteDocumentResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=data__pb2.SearchRequest.FromString,
                    response_serializer=data__pb2.SearchResponse.SerializeToString,
            ),
            'HybridSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.HybridSearch,
                    request_deserializer=data__pb2.HybridSearchRequest.FromString,
                    response_serializer=data__pb2.SearchResponse.SerializeToString,
            ),
            'RegisterParser': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterParser,
                    request_deserializer=data__pb2.RegisterParserRequest.FromString,
                    response_serializer=data__pb2.RegisterParserResponse.SerializeToString,
            ),
            'RegisterChunkingStrategy': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterChunkingStrategy,
                    request_deserializer=data__pb2.RegisterChunkingStrategyRequest.FromString,
                    response_serializer=data__pb2.RegisterChunkingStrategyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'data.DataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('data.DataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataService(object):
    """Listing 5.24
    """

    @staticmethod
    def CreateIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/CreateIndex',
            data__pb2.CreateIndexRequest.SerializeToString,
            data__pb2.IndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/GetIndex',
            data__pb2.GetIndexRequest.SerializeToString,
            data__pb2.IndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListIndexes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ListIndexes',
            data__pb2.ListIndexesRequest.SerializeToString,
            data__pb2.ListIndexesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/DeleteIndex',
            data__pb2.DeleteIndexRequest.SerializeToString,
            data__pb2.DeleteIndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/IngestDocument',
            data__pb2.IngestDocumentRequest.SerializeToString,
            data__pb2.IngestJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIngestJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/GetIngestJob',
            data__pb2.GetIngestJobRequest.SerializeToString,
            data__pb2.IngestJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ListDocuments',
            data__pb2.ListDocumentsRequest.SerializeToString,
            data__pb2.ListDocumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/GetDocument',
            data__pb2.GetDocumentRequest.SerializeToString,
            data__pb2.DocumentMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/DeleteDocument',
            data__pb2.DeleteDocumentRequest.SerializeToString,
            data__pb2.DeleteDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/Search',
            data__pb2.SearchRequest.SerializeToString,
            data__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HybridSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/HybridSearch',
            data__pb2.HybridSearchRequest.SerializeToString,
            data__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterParser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/RegisterParser',
            data__pb2.RegisterParserRequest.SerializeToString,
            data__pb2.RegisterParserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterChunkingStrategy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/RegisterChunkingStrategy',
            data__pb2.RegisterChunkingStrategyRequest.SerializeToString,
            data__pb2.RegisterChunkingStrategyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
