# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import guardrails_pb2 as guardrails__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in guardrails_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GuardrailsServiceStub(object):
    """Listing 6.19
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ValidateInput = channel.unary_unary(
                '/guardrails.GuardrailsService/ValidateInput',
                request_serializer=guardrails__pb2.ValidateInputRequest.SerializeToString,
                response_deserializer=guardrails__pb2.ValidateInputResponse.FromString,
                _registered_method=True)
        self.FilterOutput = channel.unary_unary(
                '/guardrails.GuardrailsService/FilterOutput',
                request_serializer=guardrails__pb2.FilterOutputRequest.SerializeToString,
                response_deserializer=guardrails__pb2.FilterOutputResponse.FromString,
                _registered_method=True)
        self.CheckPolicy = channel.unary_unary(
                '/guardrails.GuardrailsService/CheckPolicy',
                request_serializer=guardrails__pb2.CheckPolicyRequest.SerializeToString,
                response_deserializer=guardrails__pb2.CheckPolicyResponse.FromString,
                _registered_method=True)
        self.ReportViolation = channel.unary_unary(
                '/guardrails.GuardrailsService/ReportViolation',
                request_serializer=guardrails__pb2.ReportViolationRequest.SerializeToString,
                response_deserializer=guardrails__pb2.ReportViolationResponse.FromString,
                _registered_method=True)


class GuardrailsServiceServicer(object):
    """Listing 6.19
    """

    def ValidateInput(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FilterOutput(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckPolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportViolation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GuardrailsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ValidateInput': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateInput,
                    request_deserializer=guardrails__pb2.ValidateInputRequest.FromString,
                    response_serializer=guardrails__pb2.ValidateInputResponse.SerializeToString,
            ),
            'FilterOutput': grpc.unary_unary_rpc_method_handler(
                    servicer.FilterOutput,
                    request_deserializer=guardrails__pb2.FilterOutputRequest.FromString,
                    response_serializer=guardrails__pb2.FilterOutputResponse.SerializeToString,
            ),
            'CheckPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckPolicy,
                    request_deserializer=guardrails__pb2.CheckPolicyRequest.FromString,
                    response_serializer=guardrails__pb2.CheckPolicyResponse.SerializeToString,
            ),
            'ReportViolation': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportViolation,
                    request_deserializer=guardrails__pb2.ReportViolationRequest.FromString,
                    response_serializer=guardrails__pb2.ReportViolationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'guardrails.GuardrailsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('guardrails.GuardrailsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GuardrailsService(object):
    """Listing 6.19
    """

    @staticmethod
    def ValidateInput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/guardrails.GuardrailsService/ValidateInput',
            guardrails__pb2.ValidateInputRequest.SerializeToString,
            guardrails__pb2.ValidateInputResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FilterOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/guardrails.GuardrailsService/FilterOutput',
            guardrails__pb2.FilterOutputRequest.SerializeToString,
            guardrails__pb2.FilterOutputResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/guardrails.GuardrailsService/CheckPolicy',
            guardrails__pb2.CheckPolicyRequest.SerializeToString,
            guardrails__pb2.CheckPolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportViolation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/guardrails.GuardrailsService/ReportViolation',
            guardrails__pb2.ReportViolationRequest.SerializeToString,
            guardrails__pb2.ReportViolationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
