# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import sessions_pb2 as sessions__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sessions_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SessionServiceStub(object):
    """Listing 4.3
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOrCreateSession = channel.unary_unary(
                '/sessions.SessionService/GetOrCreateSession',
                request_serializer=sessions__pb2.GetOrCreateSessionRequest.SerializeToString,
                response_deserializer=sessions__pb2.GetOrCreateSessionResponse.FromString,
                _registered_method=True)
        self.ListSessions = channel.unary_unary(
                '/sessions.SessionService/ListSessions',
                request_serializer=sessions__pb2.ListSessionsRequest.SerializeToString,
                response_deserializer=sessions__pb2.ListSessionsResponse.FromString,
                _registered_method=True)
        self.AddMessages = channel.unary_unary(
                '/sessions.SessionService/AddMessages',
                request_serializer=sessions__pb2.AddMessagesRequest.SerializeToString,
                response_deserializer=sessions__pb2.AddMessagesResponse.FromString,
                _registered_method=True)
        self.GetMessages = channel.unary_unary(
                '/sessions.SessionService/GetMessages',
                request_serializer=sessions__pb2.GetMessagesRequest.SerializeToString,
                response_deserializer=sessions__pb2.GetMessagesResponse.FromString,
                _registered_method=True)
        self.DeleteSession = channel.unary_unary(
                '/sessions.SessionService/DeleteSession',
                request_serializer=sessions__pb2.DeleteSessionRequest.SerializeToString,
                response_deserializer=sessions__pb2.DeleteSessionResponse.FromString,
                _registered_method=True)
        self.SaveMemory = channel.unary_unary(
                '/sessions.SessionService/SaveMemory',
                request_serializer=sessions__pb2.SaveMemoryRequest.SerializeToString,
                response_deserializer=sessions__pb2.SaveMemoryResponse.FromString,
                _registered_method=True)
        self.GetMemory = channel.unary_unary(
                '/sessions.SessionService/GetMemory',
                request_serializer=sessions__pb2.GetMemoryRequest.SerializeToString,
                response_deserializer=sessions__pb2.GetMemoryResponse.FromString,
                _registered_method=True)
        self.DeleteMemory = channel.unary_unary(
                '/sessions.SessionService/DeleteMemory',
                request_serializer=sessions__pb2.DeleteMemoryRequest.SerializeToString,
                response_deserializer=sessions__pb2.DeleteMemoryResponse.FromString,
                _registered_method=True)
        self.ClearUserMemory = channel.unary_unary(
                '/sessions.SessionService/ClearUserMemory',
                request_serializer=sessions__pb2.ClearUserMemoryRequest.SerializeToString,
                response_deserializer=sessions__pb2.ClearUserMemoryResponse.FromString,
                _registered_method=True)


class SessionServiceServicer(object):
    """Listing 4.3
    """

    def GetOrCreateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveMemory(self, request, context):
        """Memory operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearUserMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SessionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetOrCreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrCreateSession,
                    request_deserializer=sessions__pb2.GetOrCreateSessionRequest.FromString,
                    response_serializer=sessions__pb2.GetOrCreateSessionResponse.SerializeToString,
            ),
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=sessions__pb2.ListSessionsRequest.FromString,
                    response_serializer=sessions__pb2.ListSessionsResponse.SerializeToString,
            ),
            'AddMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.AddMessages,
                    request_deserializer=sessions__pb2.AddMessagesRequest.FromString,
                    response_serializer=sessions__pb2.AddMessagesResponse.SerializeToString,
            ),
            'GetMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMessages,
                    request_deserializer=sessions__pb2.GetMessagesRequest.FromString,
                    response_serializer=sessions__pb2.GetMessagesResponse.SerializeToString,
            ),
            'DeleteSession': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSession,
                    request_deserializer=sessions__pb2.DeleteSessionRequest.FromString,
                    response_serializer=sessions__pb2.DeleteSessionResponse.SerializeToString,
            ),
            'SaveMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveMemory,
                    request_deserializer=sessions__pb2.SaveMemoryRequest.FromString,
                    response_serializer=sessions__pb2.SaveMemoryResponse.SerializeToString,
            ),
            'GetMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMemory,
                    request_deserializer=sessions__pb2.GetMemoryRequest.FromString,
                    response_serializer=sessions__pb2.GetMemoryResponse.SerializeToString,
            ),
            'DeleteMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMemory,
                    request_deserializer=sessions__pb2.DeleteMemoryRequest.FromString,
                    response_serializer=sessions__pb2.DeleteMemoryResponse.SerializeToString,
            ),
            'ClearUserMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearUserMemory,
                    request_deserializer=sessions__pb2.ClearUserMemoryRequest.FromString,
                    response_serializer=sessions__pb2.ClearUserMemoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sessions.SessionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sessions.SessionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SessionService(object):
    """Listing 4.3
    """

    @staticmethod
    def GetOrCreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sessions.SessionService/GetOrCreateSession',
            sessions__pb2.GetOrCreateSessionRequest.SerializeToString,
            sessions__pb2.GetOrCreateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sessions.SessionService/ListSessions',
            sessions__pb2.ListSessionsRequest.SerializeToString,
            sessions__pb2.ListSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sessions.SessionService/AddMessages',
            sessions__pb2.AddMessagesRequest.SerializeToString,
            sessions__pb2.AddMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sessions.SessionService/GetMessages',
            sessions__pb2.GetMessagesRequest.SerializeToString,
            sessions__pb2.GetMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sessions.SessionService/DeleteSession',
            sessions__pb2.DeleteSessionRequest.SerializeToString,
            sessions__pb2.DeleteSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sessions.SessionService/SaveMemory',
            sessions__pb2.SaveMemoryRequest.SerializeToString,
            sessions__pb2.SaveMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sessions.SessionService/GetMemory',
            sessions__pb2.GetMemoryRequest.SerializeToString,
            sessions__pb2.GetMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sessions.SessionService/DeleteMemory',
            sessions__pb2.DeleteMemoryRequest.SerializeToString,
            sessions__pb2.DeleteMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearUserMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sessions.SessionService/ClearUserMemory',
            sessions__pb2.ClearUserMemoryRequest.SerializeToString,
            sessions__pb2.ClearUserMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
