# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import tools_pb2 as tools__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tools_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ToolServiceStub(object):
    """Listing 6.1
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterTool = channel.unary_unary(
                '/tools.ToolService/RegisterTool',
                request_serializer=tools__pb2.RegisterToolRequest.SerializeToString,
                response_deserializer=tools__pb2.RegisterToolResponse.FromString,
                _registered_method=True)
        self.DiscoverTools = channel.unary_unary(
                '/tools.ToolService/DiscoverTools',
                request_serializer=tools__pb2.DiscoverToolsRequest.SerializeToString,
                response_deserializer=tools__pb2.DiscoverToolsResponse.FromString,
                _registered_method=True)
        self.ExecuteTool = channel.unary_unary(
                '/tools.ToolService/ExecuteTool',
                request_serializer=tools__pb2.ExecuteToolRequest.SerializeToString,
                response_deserializer=tools__pb2.ExecuteToolResponse.FromString,
                _registered_method=True)
        self.ValidateTool = channel.unary_unary(
                '/tools.ToolService/ValidateTool',
                request_serializer=tools__pb2.ValidateToolRequest.SerializeToString,
                response_deserializer=tools__pb2.ValidateToolResponse.FromString,
                _registered_method=True)


class ToolServiceServicer(object):
    """Listing 6.1
    """

    def RegisterTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DiscoverTools(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ToolServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterTool': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterTool,
                    request_deserializer=tools__pb2.RegisterToolRequest.FromString,
                    response_serializer=tools__pb2.RegisterToolResponse.SerializeToString,
            ),
            'DiscoverTools': grpc.unary_unary_rpc_method_handler(
                    servicer.DiscoverTools,
                    request_deserializer=tools__pb2.DiscoverToolsRequest.FromString,
                    response_serializer=tools__pb2.DiscoverToolsResponse.SerializeToString,
            ),
            'ExecuteTool': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTool,
                    request_deserializer=tools__pb2.ExecuteToolRequest.FromString,
                    response_serializer=tools__pb2.ExecuteToolResponse.SerializeToString,
            ),
            'ValidateTool': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateTool,
                    request_deserializer=tools__pb2.ValidateToolRequest.FromString,
                    response_serializer=tools__pb2.ValidateToolResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tools.ToolService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tools.ToolService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ToolService(object):
    """Listing 6.1
    """

    @staticmethod
    def RegisterTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tools.ToolService/RegisterTool',
            tools__pb2.RegisterToolRequest.SerializeToString,
            tools__pb2.RegisterToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DiscoverTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tools.ToolService/DiscoverTools',
            tools__pb2.DiscoverToolsRequest.SerializeToString,
            tools__pb2.DiscoverToolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tools.ToolService/ExecuteTool',
            tools__pb2.ExecuteToolRequest.SerializeToString,
            tools__pb2.ExecuteToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tools.ToolService/ValidateTool',
            tools__pb2.ValidateToolRequest.SerializeToString,
            tools__pb2.ValidateToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
