# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import workflow_pb2 as workflow__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in workflow_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkflowServiceStub(object):
    """Listing 8.21
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWorkflow = channel.unary_unary(
                '/workflow.WorkflowService/RegisterWorkflow',
                request_serializer=workflow__pb2.RegisterWorkflowRequest.SerializeToString,
                response_deserializer=workflow__pb2.RegisterWorkflowResponse.FromString,
                _registered_method=True)
        self.GetWorkflow = channel.unary_unary(
                '/workflow.WorkflowService/GetWorkflow',
                request_serializer=workflow__pb2.GetWorkflowRequest.SerializeToString,
                response_deserializer=workflow__pb2.GetWorkflowResponse.FromString,
                _registered_method=True)
        self.ListWorkflows = channel.unary_unary(
                '/workflow.WorkflowService/ListWorkflows',
                request_serializer=workflow__pb2.ListWorkflowsRequest.SerializeToString,
                response_deserializer=workflow__pb2.ListWorkflowsResponse.FromString,
                _registered_method=True)
        self.UpdateWorkflow = channel.unary_unary(
                '/workflow.WorkflowService/UpdateWorkflow',
                request_serializer=workflow__pb2.UpdateWorkflowRequest.SerializeToString,
                response_deserializer=workflow__pb2.UpdateWorkflowResponse.FromString,
                _registered_method=True)
        self.DeleteWorkflow = channel.unary_unary(
                '/workflow.WorkflowService/DeleteWorkflow',
                request_serializer=workflow__pb2.DeleteWorkflowRequest.SerializeToString,
                response_deserializer=workflow__pb2.DeleteWorkflowResponse.FromString,
                _registered_method=True)
        self.DeployWorkflow = channel.unary_unary(
                '/workflow.WorkflowService/DeployWorkflow',
                request_serializer=workflow__pb2.DeployWorkflowRequest.SerializeToString,
                response_deserializer=workflow__pb2.DeployWorkflowResponse.FromString,
                _registered_method=True)
        self.GetDeploymentStatus = channel.unary_unary(
                '/workflow.WorkflowService/GetDeploymentStatus',
                request_serializer=workflow__pb2.GetDeploymentStatusRequest.SerializeToString,
                response_deserializer=workflow__pb2.GetDeploymentStatusResponse.FromString,
                _registered_method=True)
        self.RollbackWorkflow = channel.unary_unary(
                '/workflow.WorkflowService/RollbackWorkflow',
                request_serializer=workflow__pb2.RollbackWorkflowRequest.SerializeToString,
                response_deserializer=workflow__pb2.RollbackWorkflowResponse.FromString,
                _registered_method=True)
        self.RegisterRoute = channel.unary_unary(
                '/workflow.WorkflowService/RegisterRoute',
                request_serializer=workflow__pb2.RegisterRouteRequest.SerializeToString,
                response_deserializer=workflow__pb2.RegisterRouteResponse.FromString,
                _registered_method=True)
        self.ListRoutes = channel.unary_unary(
                '/workflow.WorkflowService/ListRoutes',
                request_serializer=workflow__pb2.ListRoutesRequest.SerializeToString,
                response_deserializer=workflow__pb2.ListRoutesResponse.FromString,
                _registered_method=True)
        self.CreateJob = channel.unary_unary(
                '/workflow.WorkflowService/CreateJob',
                request_serializer=workflow__pb2.CreateJobRequest.SerializeToString,
                response_deserializer=workflow__pb2.CreateJobResponse.FromString,
                _registered_method=True)
        self.GetJobStatus = channel.unary_unary(
                '/workflow.WorkflowService/GetJobStatus',
                request_serializer=workflow__pb2.GetJobStatusRequest.SerializeToString,
                response_deserializer=workflow__pb2.GetJobStatusResponse.FromString,
                _registered_method=True)
        self.UpdateJobProgress = channel.unary_unary(
                '/workflow.WorkflowService/UpdateJobProgress',
                request_serializer=workflow__pb2.UpdateJobProgressRequest.SerializeToString,
                response_deserializer=workflow__pb2.UpdateJobProgressResponse.FromString,
                _registered_method=True)
        self.SaveJobCheckpoint = channel.unary_unary(
                '/workflow.WorkflowService/SaveJobCheckpoint',
                request_serializer=workflow__pb2.SaveJobCheckpointRequest.SerializeToString,
                response_deserializer=workflow__pb2.SaveJobCheckpointResponse.FromString,
                _registered_method=True)
        self.CompleteJob = channel.unary_unary(
                '/workflow.WorkflowService/CompleteJob',
                request_serializer=workflow__pb2.CompleteJobRequest.SerializeToString,
                response_deserializer=workflow__pb2.CompleteJobResponse.FromString,
                _registered_method=True)
        self.FailJob = channel.unary_unary(
                '/workflow.WorkflowService/FailJob',
                request_serializer=workflow__pb2.FailJobRequest.SerializeToString,
                response_deserializer=workflow__pb2.FailJobResponse.FromString,
                _registered_method=True)
        self.CancelJob = channel.unary_unary(
                '/workflow.WorkflowService/CancelJob',
                request_serializer=workflow__pb2.CancelJobRequest.SerializeToString,
                response_deserializer=workflow__pb2.CancelJobResponse.FromString,
                _registered_method=True)


class WorkflowServiceServicer(object):
    """Listing 8.21
    """

    def RegisterWorkflow(self, request, context):
        """Registry
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWorkflows(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeployWorkflow(self, request, context):
        """Deployment
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeploymentStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RollbackWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterRoute(self, request, context):
        """Routing — Workflow Service pushes routes; gateway re-hydrates on startup.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRoutes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateJob(self, request, context):
        """Async jobs (Listing 8.10–8.11)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateJobProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveJobCheckpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FailJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkflowServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorkflow,
                    request_deserializer=workflow__pb2.RegisterWorkflowRequest.FromString,
                    response_serializer=workflow__pb2.RegisterWorkflowResponse.SerializeToString,
            ),
            'GetWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkflow,
                    request_deserializer=workflow__pb2.GetWorkflowRequest.FromString,
                    response_serializer=workflow__pb2.GetWorkflowResponse.SerializeToString,
            ),
            'ListWorkflows': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWorkflows,
                    request_deserializer=workflow__pb2.ListWorkflowsRequest.FromString,
                    response_serializer=workflow__pb2.ListWorkflowsResponse.SerializeToString,
            ),
            'UpdateWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateWorkflow,
                    request_deserializer=workflow__pb2.UpdateWorkflowRequest.FromString,
                    response_serializer=workflow__pb2.UpdateWorkflowResponse.SerializeToString,
            ),
            'DeleteWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteWorkflow,
                    request_deserializer=workflow__pb2.DeleteWorkflowRequest.FromString,
                    response_serializer=workflow__pb2.DeleteWorkflowResponse.SerializeToString,
            ),
            'DeployWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.DeployWorkflow,
                    request_deserializer=workflow__pb2.DeployWorkflowRequest.FromString,
                    response_serializer=workflow__pb2.DeployWorkflowResponse.SerializeToString,
            ),
            'GetDeploymentStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeploymentStatus,
                    request_deserializer=workflow__pb2.GetDeploymentStatusRequest.FromString,
                    response_serializer=workflow__pb2.GetDeploymentStatusResponse.SerializeToString,
            ),
            'RollbackWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.RollbackWorkflow,
                    request_deserializer=workflow__pb2.RollbackWorkflowRequest.FromString,
                    response_serializer=workflow__pb2.RollbackWorkflowResponse.SerializeToString,
            ),
            'RegisterRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterRoute,
                    request_deserializer=workflow__pb2.RegisterRouteRequest.FromString,
                    response_serializer=workflow__pb2.RegisterRouteResponse.SerializeToString,
            ),
            'ListRoutes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRoutes,
                    request_deserializer=workflow__pb2.ListRoutesRequest.FromString,
                    response_serializer=workflow__pb2.ListRoutesResponse.SerializeToString,
            ),
            'CreateJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateJob,
                    request_deserializer=workflow__pb2.CreateJobRequest.FromString,
                    response_serializer=workflow__pb2.CreateJobResponse.SerializeToString,
            ),
            'GetJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobStatus,
                    request_deserializer=workflow__pb2.GetJobStatusRequest.FromString,
                    response_serializer=workflow__pb2.GetJobStatusResponse.SerializeToString,
            ),
            'UpdateJobProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateJobProgress,
                    request_deserializer=workflow__pb2.UpdateJobProgressRequest.FromString,
                    response_serializer=workflow__pb2.UpdateJobProgressResponse.SerializeToString,
            ),
            'SaveJobCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveJobCheckpoint,
                    request_deserializer=workflow__pb2.SaveJobCheckpointRequest.FromString,
                    response_serializer=workflow__pb2.SaveJobCheckpointResponse.SerializeToString,
            ),
            'CompleteJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteJob,
                    request_deserializer=workflow__pb2.CompleteJobRequest.FromString,
                    response_serializer=workflow__pb2.CompleteJobResponse.SerializeToString,
            ),
            'FailJob': grpc.unary_unary_rpc_method_handler(
                    servicer.FailJob,
                    request_deserializer=workflow__pb2.FailJobRequest.FromString,
                    response_serializer=workflow__pb2.FailJobResponse.SerializeToString,
            ),
            'CancelJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelJob,
                    request_deserializer=workflow__pb2.CancelJobRequest.FromString,
                    response_serializer=workflow__pb2.CancelJobResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'workflow.WorkflowService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('workflow.WorkflowService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkflowService(object):
    """Listing 8.21
    """

    @staticmethod
    def RegisterWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflow.WorkflowService/RegisterWorkflow',
            workflow__pb2.RegisterWorkflowRequest.SerializeToString,
            workflow__pb2.RegisterWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflow.WorkflowService/GetWorkflow',
            workflow__pb2.GetWorkflowRequest.SerializeToString,
            workflow__pb2.GetWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWorkflows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflow.WorkflowService/ListWorkflows',
            workflow__pb2.ListWorkflowsRequest.SerializeToString,
            workflow__pb2.ListWorkflowsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflow.WorkflowService/UpdateWorkflow',
            workflow__pb2.UpdateWorkflowRequest.SerializeToString,
            workflow__pb2.UpdateWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflow.WorkflowService/DeleteWorkflow',
            workflow__pb2.DeleteWorkflowRequest.SerializeToString,
            workflow__pb2.DeleteWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeployWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflow.WorkflowService/DeployWorkflow',
            workflow__pb2.DeployWorkflowRequest.SerializeToString,
            workflow__pb2.DeployWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeploymentStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflow.WorkflowService/GetDeploymentStatus',
            workflow__pb2.GetDeploymentStatusRequest.SerializeToString,
            workflow__pb2.GetDeploymentStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RollbackWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflow.WorkflowService/RollbackWorkflow',
            workflow__pb2.RollbackWorkflowRequest.SerializeToString,
            workflow__pb2.RollbackWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflow.WorkflowService/RegisterRoute',
            workflow__pb2.RegisterRouteRequest.SerializeToString,
            workflow__pb2.RegisterRouteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRoutes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflow.WorkflowService/ListRoutes',
            workflow__pb2.ListRoutesRequest.SerializeToString,
            workflow__pb2.ListRoutesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflow.WorkflowService/CreateJob',
            workflow__pb2.CreateJobRequest.SerializeToString,
            workflow__pb2.CreateJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflow.WorkflowService/GetJobStatus',
            workflow__pb2.GetJobStatusRequest.SerializeToString,
            workflow__pb2.GetJobStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateJobProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflow.WorkflowService/UpdateJobProgress',
            workflow__pb2.UpdateJobProgressRequest.SerializeToString,
            workflow__pb2.UpdateJobProgressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveJobCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflow.WorkflowService/SaveJobCheckpoint',
            workflow__pb2.SaveJobCheckpointRequest.SerializeToString,
            workflow__pb2.SaveJobCheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflow.WorkflowService/CompleteJob',
            workflow__pb2.CompleteJobRequest.SerializeToString,
            workflow__pb2.CompleteJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FailJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflow.WorkflowService/FailJob',
            workflow__pb2.FailJobRequest.SerializeToString,
            workflow__pb2.FailJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflow.WorkflowService/CancelJob',
            workflow__pb2.CancelJobRequest.SerializeToString,
            workflow__pb2.CancelJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
